#!/usr/bin/env sh

confirm() {
    printf "\e[33mconfirm:\e[0m $1? "
    read x < /dev/tty
}

wrapper() {
    cd
    if [ -e .config ]; then
        confirm "remove existing .config"
        if [ "$x" = y ]; then
            rm -rf .config
        else
            exit 0
        fi
    fi
    git clone -q https://github.com/azdavis/config .config
    chmod 700 .config
    confirm "remove existing dotfiles"
    if [ "$x" = y ]; then
        .config/bin/do-dotfiles
    fi
}

wrapper
