set nocompatible

syntax enable
filetype plugin indent on

set backspace=indent,eol,start
set colorcolumn=81
set expandtab
set hlsearch
set number
set ruler
set shiftwidth=2
set showcmd
set smartindent
set smarttab
set tabstop=2
