set nocompatible

set autoindent
set autoread
set backspace=indent,eol,start
set expandtab
set incsearch
set number
set shiftwidth=4
set smarttab
set tabstop=4
set ttimeout
set ttimeoutlen=100
set viminfo="NONE"
set wildmenu

syntax enable
filetype plugin indent on
