se nocompatible

se autoindent
se autoread
se backspace=indent,eol,start
se colorcolumn=79
se expandtab
se ignorecase
se incsearch
se listchars=space:·,eol:¬,tab:>-
se number
se shiftwidth=4
se smarttab
se tabstop=4
se ttimeout
se ttimeoutlen=100
se viminfo="none"
se wildmenu

hi colorcolumn ctermbg=grey
hi comment ctermfg=grey
hi constant ctermfg=blue
hi diffadded ctermfg=green
hi difffile ctermfg=cyan
hi diffline ctermfg=cyan
hi diffremoved ctermfg=red
hi diffsubname ctermfg=black
hi identifier ctermfg=red
hi linenr ctermfg=grey
hi special ctermfg=cyan
hi statement ctermfg=red
hi string ctermfg=yellow
hi type ctermfg=red

syn enable
filet plugin indent on
