local last_run="$HOME/.config/update.last-run"
if [ ! -e "$last_run" ] \
|| expr "$(date +%s)" - "$(cat "$last_run")" ">=" 604800 >/dev/null; then
    echo "==> updating dotfiles"
    "$HOME/.config/bin/update-dotfiles"
fi
