last_update="$HOME/.config/update.last-run"
if [ ! -e "$last_update" ] \
|| expr "$(date +%s)" - "$(cat "$last_update")" ">=" 604800 >/dev/null; then
    echo "==> updating dotfiles"
    "$HOME/.config/bin/update-dotfiles"
fi
unset last_update
