export \
	EDITOR="subl" \
	HOMEBREW_CASK_OPTS="--appdir=/Applications" \
	HOMEBREW_NO_ANALYTICS="1" \
	HOMEBREW_NO_EMOJI="1" \
	HOMEBREW_NO_INSECURE_REDIRECT="1" \
	LESS="-x4" \
	LESSHISTFILE="/dev/null" \
	LS_COLORS="di=34:ln=35:so=32:pi=33:ex=31:bd=7;36:cd=7;33:su=7;31:sg=7;36:tw=7;32:ow=7;33:st=7;34" \
	MORE="-x4" \
	RLWRAP_HOME="/dev/null"
