#!/usr/bin/env zsh

source "$HOME/.config/misc/base.sh" || exit 1

cd "$HOME/.config"

interval='604800'
log='misc/auto_update.log'
[[ -f "$log" ]] || echo 0 > "$log"

current="$(date +%s)"
last="$(cat "$log")"
difference="$(expr "$current" - "$last")"

if [[ "$difference" -ge "$interval" ]]; then
  echo 'updating ~/.config...'
  util/update
  echo "$current" > "$log"
fi
