#!/usr/bin/env zsh

source "$HOME/.config/misc/base.sh" || exit 1

cd "$HOME/.config"

interval='604800'
current="$(date +%s)"
last="$(cat 'misc/update.log' 2> /dev/null || echo 0)"
difference="$(expr "$current" - "$last")"

if [[ "$difference" -ge "$interval" ]]; then
  echo 'updating ~/.config...'
  util/update
else
  exit 1
fi
