#!/usr/bin/env zsh

source "$HOME/.config/misc/base.sh" || exit 1

cd "$HOME/.config"

interval='604800'
current="$(date +%s)"
last="$(cat 'misc/update.log' 2> /dev/null || echo 0)"
difference="$(expr "$current" - "$last")"

[[ "$difference" -lt "$interval" ]] && exit 1
echo 'updating ~/.config...'
util/update
