#!/usr/bin/env zsh

set -euo pipefail
IFS=$'\n\t'
err() { echo "error: $1" && exit 1 }
if [[ "$USER" == 'root' ]]; then err 'do not run as root'; fi

remote='https://github.com/azdavis/config.git'
name='.config'
tmp=".tmp $$ $RANDOM $(date)"

cd "$HOME"

if [[ -d "$name" ]]; then
  [[ -d "$name/.git" ]] && err 'already installed'
  zip -r "backup$name.zip" "$name"
else
  mkdir -p "$name"
fi

git clone --branch master --single-branch "$remote" "$tmp"
mv "$tmp"/.* "$tmp"/* "$name"
rmdir "$tmp"
echo 'install complete'
