#!/usr/bin/env zsh

set -euo pipefail
IFS=$'\n\t'
err() { echo "\e[31merror:\e[0m $1" && exit 1 }
[[ "$USER" == 'root' ]] && err 'do not run as root'

remote='https://github.com/azdavis/config.git'
name='.config'
tmp=".tmp$(date +%s)"

cd

if [[ -d "$name" ]]; then
  [[ -d "$name/.git" ]] && err 'already installed'
  zip -r "backup$name.zip" "$name"
else
  mkdir -p "$name"
fi

which git > /dev/null || xcode-select --install

git clone --branch master --single-branch "$remote" "$tmp"
mv "$tmp"/.* "$tmp"/* "$name"
rmdir "$tmp"
echo 'install complete'
