#!/usr/bin/env zsh

_() {

abort() { echo "\e[31merror:\e[0m $1" && exit 1 }
[[ "$ZSH_VERSION" ]] || abort 'only run with zsh'
[[ "$USER" == 'root' ]] && abort 'do not run as root'

set -euo pipefail
IFS=$'\n\t'

remote='https://github.com/azdavis/config.git'
name='.config'
tmp=".tmp-$$-$RANDOM-$(date +%s)"

cd
if [[ -d "$name" ]]; then
    [[ -d "$name/.git" ]] && abort 'already installed'
    zip -r "backup-$name.zip" "$name"
else
    mkdir -p "$name"
fi

which git > /dev/null || xcode-select --install

git clone --branch master --single-branch "$remote" "$tmp"
mv "$tmp"/.* "$tmp"/* "$name"
rmdir "$tmp"
echo 'install complete'

true

}

_
