#!/usr/bin/env zsh

source "$HOME/.config/misc/base.sh" || exit 1

cd "$HOME/.config"

if pgrep -f 'Sublime Text' > /dev/null; then
  err 'sublime text must not be running'
elif [[ -n "$(git log origin/master..master)" ]]; then
  err 'there are unpushed changes'
elif ! ping -c 1 -t 3 github.com &> /dev/null; then
  err 'could not connect to github.com'
elif [[ "$(
  curl -fsSL -m 3 -w %{http_code} \
  -H Accept:\ application/vnd.github.chitauri-preview+sha \
  -H If-None-Match:\ \"$(git rev-parse HEAD)\" \
  https://api.github.com/repos/azdavis/config/commits/master
)" == '304' ]]; then
  echo 'already up-to-date'
else
  echo 'updating ~/.config...'
  git stash save --quiet
  git checkout --quiet master
  git fetch --quiet origin master
  git merge --ff-only origin/master master
  [[ -n "$(git stash list)" ]] && git stash pop --quiet
  echo 'iTerm may need to be restarted to finish applying this update'
fi

date +%s > 'misc/update.last-run'

true
