#!/usr/bin/env zsh

source "$HOME/.config/misc/base"

cd "$HOME/.config"

if pgrep -f 'Sublime Text' > /dev/null; then
  err 'sublime text must not be running'
elif [[ -n "$(git status --porcelain)" ]]; then
  err 'there are uncommitted changes'
elif [[ -n "$(git log origin/master..master)" ]]; then
  err 'there are unpushed changes'
elif [[ "$(
  curl -fsSL -m 3 -w %{http_code} \
  -H Accept:\ application/vnd.github.chitauri-preview+sha \
  -H If-None-Match:\ \"$(git rev-parse HEAD)\" \
  https://api.github.com/repos/azdavis/config/commits/master
)" == '304' ]]; then
  echo 'already up-to-date' && exit
fi

git checkout --quiet master
git fetch --quiet origin master
git merge --ff-only origin/master master
