#!/bin/sh

set -eu

if command -v brew > /dev/null; then
  brew update
  brew upgrade
  brew cleanup
else
  echo "no brew"
fi

sf="$HOME/.site-functions"
mkdir -p "$sf"

if command -v rustup > /dev/null; then
  rustup self update
  rustup update
  rustup completions zsh rustup > "$sf/_rustup"
  rustup completions zsh cargo > "$sf/_cargo"
else
  echo "no rustup"
fi
