#!/usr/bin/env zsh

_() {

set -euo pipefail
IFS=$'\n\t'

abort() {
    echo "\e[31merror:\e[0m $1" && exit 1
}

[[ "$USER" == "root" ]] && abort "do not run as root"

remote="https://github.com/azdavis/config.git"
name=".config"
tmp="$(mktemp -d ./clone-$name-XXXXXXXX)"

cd
if [[ -d "$name" ]]; then
    [[ -d "$name/.git" ]] && abort "already installed"
    backup="$(mktemp -d ./backup-$name-XXXXXXXX)"
    mv "$name"/.* "$name"/* "$backup"
else
    mkdir -p "$name"
fi

echo "installing..."
which git > /dev/null || xcode-select --install
git clone -qb master --single-branch "$remote" "$tmp"
mv "$tmp"/.* "$tmp"/* "$name"
rmdir "$tmp"
echo "install complete"

true

}

_
