#!/usr/bin/env sh

wrapper() {

set -euo pipefail
IFS=$'\n\t'

abort() {
    echo 1>&2 $'\e[31merror:\e[0m' "$1"
    exit 1
}

[[ "$USER" == "root" ]] && abort "do not run as root"

cd "$HOME"

repo="azdavis/config"
remote="https://github.com/$repo.git"
name=".config"
tmp="$(mktemp -d ./gitclone-$name-XXXXXXXX)"
trap "rm -rf \"$tmp\"" EXIT

if [[ -d "$name" ]]; then
    [[ -d "$name/.git" ]] && abort "$repo already installed"
    backup="$(mktemp -d ./backup-$name-XXXXXXXX)"
    mv "$name"/.* "$name"/* "$backup"
else
    mkdir -p "$name"
fi

echo "installing..."
which git > /dev/null || xcode-select --install
git clone -qb master --single-branch "$remote" "$tmp"
mv "$tmp"/.* "$tmp"/* "$name"
echo "$repo install complete"

}

wrapper
true
