#!/usr/bin/env zsh

_() {

set -euo pipefail
IFS=$'\n\t'

abort() {
    echo "\e[31merror:\e[0m $1" && exit 1
}

[[ "$USER" == "root" ]] && abort "do not run as root"

repo="azdavis/config"
remote="https://github.com/$repo.git"
name=".config"

cd "$HOME"

tmp="$(mktemp -d ./clone-$name-XXXXXXXX)"
trap "rmdir \"$tmp\"" EXIT

if [[ -d "$name" ]]; then
    [[ -d "$name/.git" ]] && abort "$repo already installed"
    backup="$(mktemp -d ./backup-$name-XXXXXXXX)"
    mv "$name"/.* "$name"/* "$backup"
else
    mkdir -p "$name"
fi

echo "installing..."
which git > /dev/null || xcode-select --install
git clone -qb master --single-branch "$remote" "$tmp"
mv "$tmp"/.* "$tmp"/* "$name"
echo "$repo install complete"

true

}

_
